# Make sure not to name your pipeline deploy, as this will conflict with the built-in deploy action
name: deploy infra and app
on:
  workflow_dispatch:
  push:
    branches:
      - main
env:
  AZURE_WEBAPP_NAME: DrakeHasTheBestTickTackToeApp456
  NODE_VERSION: "14.x"
jobs:
  validate-credentials:
    name: validate azure credentials
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Log in to Azure
        run: |
          az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}
# generate credentials using this command, then store them in GitHub secrets
# az ad sp create-for-rbac --name "pipelineCredentials" --role contributor --scopes /subscriptions/{subscription-id}/resourceGroups/{resource-group} 

      - name: logout
        run: |
          az logout

  build-infrastructure:
    name: build infrastructure
    needs: validate-credentials
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Log in to Azure
        run: |
          az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}
      
      - name: build infrastructure
        run: |
              az deployment group create \
                --resource-group 'IacReferenceForCodeAlong' \
                --template-file './infra/main.bicep' \
                --parameters '@./infra/main.parameters.json' \
                --parameters appName=${{env.AZURE_WEBAPP_NAME}} 
  
  build-app:
    name: build react app
    needs: build-infrastructure
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Use node.js ${{env.NODE_VERSION}}
        uses: actions/setup-node@v1
        with:
          node-version: ${{env.NODE_VERSION}}

      - name: npm install and build
        run: |
          cd front-end 
          npm install
          npm run build

      - name: upload build artifacts
        run: |
          mkdir -p ${{github.workspace}}/frontend-app
          cp -R src/frontend/build ${{github.workspace}}/frontend-app

  deploy-app:
    name: deploy react app
    needs: build-app
    runs-on: ubuntu-latest
    steps:
      - name: downloading artifact
        run: |
          mkdir -p ${{github.workspace}}/frontend-app
          curl -sL -o ${{github.workspace}}/frontend-app/artifact.zip <DOWNLOAD_URL>
          unzip ${{github.workspace}}/frontend-app/artifact.zip -d ${{github.workspace}}/frontend-app

      - name: deploy to azure web app
        id: deploy-to-web-app
        run: |
          az webapp deployment source config-zip \
            --resource-group 'IacReferenceForCodeAlong' \
            --name ${{env.AZURE_WEBAPP_NAME}} \
            --src ./frontend-app.zip

  logout:
    name: log out of azure
    needs: deploy-app
    runs-on: ubuntu-latest
    steps:
      - name: logout
        run: |
          az logout